services:
    backend:
        build:
            context: ./backend
        env_file:
            - .env
        ports:
            - '8080:8080'
        restart: unless-stopped
        privileged: true
        devices:
            - "/dev:/dev"
        volumes:
            - "/run/udev:/run/udev:ro"
            # Required for Pi Camera DMA heap allocation
            - "/dev/dma_heap:/dev/dma_heap"
        group_add:
            - video
        networks:
            - picam

    frontend:
        build:
            context: ./frontend
        depends_on:
            - backend
        ports:
            - '3000:80'
        restart: unless-stopped
        networks:
            - picam

networks:
    picam:
        driver: bridge
