version: '3.9'

services:
    backend:
        build:
            context: ./backend
        environment:
            BACKEND_HOST: 0.0.0.0
            BACKEND_PORT: 8080
            FRAME_RATE: 12
            FRAME_WIDTH: 1280
            FRAME_HEIGHT: 720
        ports:
            - '8080:8080'
        restart: unless-stopped
        networks:
            - picam

    frontend:
        build:
            context: ./frontend
            args:
                VITE_BACKEND_URL: http://backend:8080
        depends_on:
            - backend
        ports:
            - '3000:4173'
        restart: unless-stopped
        networks:
            - picam

networks:
    picam:
        driver: bridge
